"""ASS (Advanced SubStation Alpha) rendering.

Ported verbatim from v0.1 ``subtitle/formatter.py`` (lines 1060-1184) plus
``compute_adaptive_subtitle_style`` from ``subtitle/controller.py`` (line 410),
which v0.1 had left in the phase orchestrator even though it is pure styling
math. The algorithms are ports, not rewrites: ``tests/regression/test_ass_port.py``
asserts the v0.1 output verbatim.

Two writers exist because the pipeline renders both a pair of independent tracks
(Chinese above English — "asynchronous" because each track keeps its own timing)
and a single Chinese track that can afford a larger font.
"""

from __future__ import annotations

from porter.config import SubtitleStyleConfig
from porter.models.subtitle import SubtitleItem
from porter.subtitles.phrasing import clean_chinese_punctuation

__all__ = [
    "compute_adaptive_subtitle_style",
    "generate_bilingual_ass",
    "generate_zh_ass",
]

#: Trailing full stops. Professional subtitles omit the sentence-final period.
#: Column order of every ``Style:`` row. Shared by both writers.
_STYLE_FORMAT = (
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
    "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
    "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
)

#: Column order of every ``Dialogue:`` row. Shared by both writers.
_EVENTS_FORMAT = (
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
)


def _ass_header(
    title: str,
    style_lines: list[str],
    play_res_x: int,
    play_res_y: int,
) -> str:
    """Build the ``[Script Info]`` / ``[V4+ Styles]`` / ``[Events]`` preamble.

    The header is byte-identical to the v0.1 ``f``-strings; factor it out only so
    the two writers cannot drift apart on the shared sections.
    """
    styles = "\n".join(style_lines)
    return (
        "[Script Info]\n"
        "; Script generated by Video Porter Skill\n"
        f"Title: {title}\n"
        "ScriptType: v4.00+\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
        "YCbCr Matrix: TV.601\n"
        f"PlayResX: {play_res_x}\n"
        f"PlayResY: {play_res_y}\n"
        "\n"
        "[V4+ Styles]\n"
        f"{_STYLE_FORMAT}\n"
        f"{styles}\n"
        "\n"
        "[Events]\n"
        f"{_EVENTS_FORMAT}\n"
    )


def compute_adaptive_subtitle_style(
    width: int,
    height: int,
    base_style: SubtitleStyleConfig | None = None,
) -> tuple[SubtitleStyleConfig, SubtitleStyleConfig, int, int]:
    """Compute aspect-ratio and resolution-adaptive subtitle styling.

    Returns ``(bilingual_style, zh_style, play_res_x, play_res_y)`` for the
    bilingual render and the pure-Chinese render respectively, along with the
    1:1 physical ``PlayRes`` dimensions.

    The ``PlayRes`` value matters: libass interprets font sizes against it, so
    declaring the real resolution stops anamorphic font squeeze on non-16:9
    videos (4:3, 3:2, 1:1). Font sizes are additionally boosted for compact
    aspect ratios because a square frame wastes less distance to the edge than a
    wide one.

    Dimensions are clamped to ``320x240`` so a probe failure cannot produce a
    zero-sized canvas (and a division by zero in the aspect ratio).
    """
    if base_style is None:
        base_style = SubtitleStyleConfig()

    w = max(width, 320)
    h = max(height, 240)
    aspect_ratio = w / h
    is_vertical = h > w

    bilingual_style = base_style.model_copy()
    zh_style = base_style.model_copy()

    if is_vertical:
        # Vertical video (e.g. 1080x1920 Shorts / Reels / TikTok)
        scale_v = h / 1920.0
        bilingual_style.zh_font_size = max(24, round(56 * scale_v))
        bilingual_style.en_font_size = max(16, round(38 * scale_v))
        bilingual_style.bilingual_zh_margin_v = max(40, round(220 * scale_v))
        bilingual_style.bilingual_en_margin_v = max(25, round(140 * scale_v))
        bilingual_style.outline_width = max(1.5, round(4.0 * scale_v, 1))
        bilingual_style.shadow = max(1.0, round(2.0 * scale_v, 1))

        zh_style.zh_font_size = max(28, round(64 * scale_v))
        zh_style.margin_v = max(35, round(180 * scale_v))
        zh_style.outline_width = max(1.5, round(4.2 * scale_v, 1))
        zh_style.shadow = max(1.0, round(2.0 * scale_v, 1))
    else:
        # Horizontal or square video (e.g. 16:9, 4:3, 3:2, 1:1)
        scale_h = h / 1080.0

        if aspect_ratio <= 1.1:
            aspect_boost = 1.25  # Square (1:1)
        elif aspect_ratio <= 1.4:
            aspect_boost = 1.18  # 4:3 (~1.33)
        elif aspect_ratio <= 1.6:
            aspect_boost = 1.12  # 3:2 / 1106x720 (~1.53)
        else:
            aspect_boost = 1.00  # 16:9 / 21:9

        # Bilingual track calculations
        b_zh_size = max(18, round(base_style.zh_font_size * scale_h * aspect_boost))
        b_en_size = max(12, round(base_style.en_font_size * scale_h * aspect_boost))
        b_en_margin = max(15, round(base_style.bilingual_en_margin_v * scale_h * aspect_boost))
        b_zh_margin = b_en_margin + b_en_size + max(6, round(12 * scale_h))

        bilingual_style.zh_font_size = b_zh_size
        bilingual_style.en_font_size = b_en_size
        bilingual_style.bilingual_en_margin_v = b_en_margin
        bilingual_style.bilingual_zh_margin_v = b_zh_margin
        bilingual_style.outline_width = max(
            1.5, round(base_style.outline_width * scale_h * aspect_boost, 1)
        )
        bilingual_style.shadow = max(1.0, round(base_style.shadow * scale_h * aspect_boost, 1))

        # Pure Chinese track calculations (larger font size for clean single track)
        zh_single_size = max(20, round(58 * scale_h * aspect_boost))
        zh_single_margin = max(15, round(base_style.margin_v * scale_h * aspect_boost))

        zh_style.zh_font_size = zh_single_size
        zh_style.margin_v = zh_single_margin
        zh_style.outline_width = max(
            1.5, round(base_style.outline_width * 1.1 * scale_h * aspect_boost, 1)
        )
        zh_style.shadow = max(1.0, round(base_style.shadow * scale_h * aspect_boost, 1))

    return bilingual_style, zh_style, w, h


def generate_bilingual_ass(
    items: list[SubtitleItem] | None = None,
    style: SubtitleStyleConfig | None = None,
    play_res_x: int = 1920,
    play_res_y: int = 1080,
    zh_items: list[SubtitleItem] | None = None,
    en_items: list[SubtitleItem] | None = None,
) -> str:
    """Generate styled bilingual ASS content.

    Three input shapes are supported, in priority order:

    1. ``zh_items`` **and** ``en_items`` — two independent tracks with unrelated
       timings (the "asynchronous" case, where a Chinese sentence spans several
       English cues).
    2. ``items`` — one list carrying both languages per cue.
    3. nothing — header only, which is a valid empty script.

    Fade transitions are emitted as ``{\\fad(in,out)}`` overrides rather than as
    a style attribute so they survive burn-in.
    """
    if style is None:
        style = SubtitleStyleConfig()

    header = _ass_header(
        "Bilingual Subtitles",
        [
            f"Style: Default,{style.zh_font},{style.zh_font_size},{style.zh_primary_color},&H000000FF,{style.outline_color},&H80000000,-1,0,0,0,100,100,0,0,1,{style.outline_width},{style.shadow},2,{style.margin_l},{style.margin_r},{style.bilingual_zh_margin_v},1",
            f"Style: SubtitleZh,{style.zh_font},{style.zh_font_size},{style.zh_primary_color},&H000000FF,{style.outline_color},&H80000000,-1,0,0,0,100,100,0,0,1,{style.outline_width},{style.shadow},2,{style.margin_l},{style.margin_r},{style.bilingual_zh_margin_v},1",
            f"Style: SubtitleEn,{style.en_font},{style.en_font_size},{style.en_primary_color},&H000000FF,{style.outline_color},&H80000000,0,0,0,0,100,100,0,0,1,{style.outline_width * 0.7:.1f},{style.shadow * 0.7:.1f},2,{style.margin_l},{style.margin_r},{style.bilingual_en_margin_v},1",
        ],
        play_res_x,
        play_res_y,
    )

    events: list[str] = []
    fade_tag = f"{{\\fad({style.fade_in_ms},{style.fade_out_ms})}}"

    if zh_items is not None and en_items is not None:
        # Dual-track asynchronous independent events
        for z in zh_items:
            zh_raw = (z.target_text or z.source_text).replace("\n", " ").strip()
            zh_clean = clean_chinese_punctuation(zh_raw)
            if zh_clean:
                text = f"{fade_tag}{{\\fn{style.zh_font}\\fs{style.zh_font_size}\\b1}}{zh_clean}"
                events.append(f"Dialogue: 1,{z.start_ass},{z.end_ass},SubtitleZh,,0,0,0,,{text}")

        for e in en_items:
            en_clean = e.source_text.replace("\n", " ").strip()
            if en_clean:
                text = f"{fade_tag}{{\\fn{style.en_font}\\fs{style.en_font_size}\\c{style.en_primary_color}&\\b0}}{en_clean}"
                events.append(f"Dialogue: 0,{e.start_ass},{e.end_ass},SubtitleEn,,0,0,0,,{text}")
    elif items:
        # Standard combined items list
        for item in items:
            start = item.start_ass
            end = item.end_ass

            if item.target_text and item.source_text and item.target_text != item.source_text:
                zh_clean = clean_chinese_punctuation(
                    item.target_text.replace("\n", " ").strip()
                )
                en_clean = item.source_text.replace("\n", " ").strip()
                zh_text = f"{fade_tag}{{\\fn{style.zh_font}\\fs{style.zh_font_size}\\b1}}{zh_clean}"
                en_text = f"{fade_tag}{{\\fn{style.en_font}\\fs{style.en_font_size}\\c{style.en_primary_color}&\\b0}}{en_clean}"
                events.append(f"Dialogue: 1,{start},{end},SubtitleZh,,0,0,0,,{zh_text}")
                events.append(f"Dialogue: 0,{start},{end},SubtitleEn,,0,0,0,,{en_text}")
            elif item.target_text:
                clean_t = clean_chinese_punctuation(
                    item.target_text.replace("\n", " ").strip()
                )
                text = f"{fade_tag}{{\\fn{style.zh_font}\\fs{style.zh_font_size}\\b1}}{clean_t}"
                events.append(f"Dialogue: 1,{start},{end},SubtitleZh,,0,0,0,,{text}")
            else:
                clean_s = item.source_text.replace("\n", " ").strip()
                text = f"{fade_tag}{{\\fn{style.en_font}\\fs{style.en_font_size}\\c{style.en_primary_color}&\\b0}}{clean_s}"
                events.append(f"Dialogue: 0,{start},{end},SubtitleEn,,0,0,0,,{text}")

    # Sort events by start time
    events.sort(key=lambda line: line.split(",")[1] if "," in line else "")

    return header + "\n".join(events) + "\n"


def generate_zh_ass(
    items: list[SubtitleItem],
    style: SubtitleStyleConfig | None = None,
    play_res_x: int = 1920,
    play_res_y: int = 1080,
) -> str:
    """Generate styled pure Chinese single-track ASS content."""
    if style is None:
        style = SubtitleStyleConfig()

    header = _ass_header(
        "Chinese Subtitles",
        [
            f"Style: Default,{style.zh_font},{style.zh_font_size},{style.zh_primary_color},&H000000FF,{style.outline_color},&H80000000,-1,0,0,0,100,100,0,0,1,{style.outline_width},{style.shadow},2,{style.margin_l},{style.margin_r},{style.margin_v},1",
        ],
        play_res_x,
        play_res_y,
    )

    events = []
    fade_tag = f"{{\\fad({style.fade_in_ms},{style.fade_out_ms})}}"
    for item in items:
        start = item.start_ass
        end = item.end_ass
        text = clean_chinese_punctuation(
            (item.target_text if item.target_text else item.source_text).replace("\n", " ").strip()
        )
        events.append(
            f"Dialogue: 0,{start},{end},Default,,0,0,0,,{fade_tag}{{\\fn{style.zh_font}\\fs{style.zh_font_size}\\b1}}{text}"
        )

    return header + "\n".join(events) + "\n"
